---
title: "**Publications**"

about:
  template: solana
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com
    - icon: github
      text: Github
      href: https://github.com

---
<div style="text-align: left">
1) <u>Quyen V. Vu</u>, Ian Sitarik,  Yang Jiang, Divya Yadav, Piyoosh Sharma,  Stephen D. Fried, Mai Suan Li, Edward P. O’Brien. **A Newly Identified Class of Protein Misfolding in All-atom Folding Simulations Consistent with Limited Proteolysis Mass Spectrometry**. [PrePrint available](https://www.biorxiv.org/content/10.1101/2022.07.19.500586v2)
1) Sarah E. Leininger, Judith Rodriguez, <u>Quyen V. Vu</u>, Yang Jiang, Mai Suan Li, Carol Deutsch, and Edward P. O’Brien. **Ribosome Elongation Kinetics of Consecutively Charged Residues Are Coupled to Electrostatic Force**, Biochemistry 2021, 60, 43, 3223–3235.
1) <u>Quyen V. Vu</u>, Yang Jiang, Mai Suan Li, Edward O'Brien. **The Driving Force for Co-translational Protein Folding is Weaker In the Ribosome Vestibule due to Greater Water Ordering** , Chemical Science 2021. 12, 11851-11857.
1) Daniel A. Nissley, <u>Quyen V. Vu</u>, Fabio Trovato, Nabeel Ahmed, Yang Jiang, Mai Suan Li, and Edward P. O’Brien. **Electrostatic Interactions Govern Extreme Nascent Protein Ejection Times from Ribosomes and Can Delay Ribosome Recycling**, J. Am. Chem. Soc. 142, 13, 6103-6110 (2020).
 </div>