---
title: "**Tools**"
# image: profile.
comments: false
about:
  template: jolla
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/qvv5013

    - icon: github
      text: Github
      href: https://github.com/qvv5013
title-block-banner: true

---
<div style="text-align: left">
# `COSMO`:

COarse-grained Simulation of intrinsically disordered prOteins with openMM.
Package utilize the customizable, high-performance of OpenMM and good science from high-quality researches.


Currently, there are four models are supported:

1) `hps_urry:` Hydropathy according to Urry scale (default, Recommended).
2) `hps_kr:`  Kapcha-Rossy scale.
   This model has parameters for nucleic acids and post-translational modification residues.
3) `hps_ss:` `hps_urry` with bonded potential.
4) `mpipi`: another model that using Wang-Frenkel short range potential instead of LJ 12-6
5) Other models can be easily implemented by defining them in `cosmo/parameters/model_parameters.py`


The package is ready for studying various problems such as, conformation dynamics of single chain, LLPS ...

(Source code is available on [Github](https://github.com/qvv5013/cosmo))

Check out docs for more details [here](https://qvv5013.github.io/docs-hpsOpenMM/)

# entanglement Analysis

There are two main version of entanglement analysis:

* The first one is characterized by the linking number of loops and the open terminal, which is composed of the whole terminal. Please check this paper for more details. This kind of entanglement can be calculated by the following code which is developed by Ian Sitarik (Penn State).
[Python version]()


* The maximum linking number between the loop and all possible segments of the terminal is calculated by the following code: [Julia version](https://github.com/qvv5013/entanglement_analysis).
There are two versions for this kind of entanglement calculation, in python and Julia. julia is much faster than Python.

</div>